/* SavePerson */

/* (ASYNC) */
export const SAVE_PERSON_INIT = 'SAVE_PERSON_INIT';
export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAILURE = 'SAVE_PERSON_FAILURE';

/* ListPerson */

/* (ASYNC) */
export const FETCH_PEOPLE_INIT = 'FETCH_PEOPLE_INIT';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';
export const FETCH_PEOPLE_SUCCESSMORE = 'FETCH_PEOPLE_SUCCESSMORE';

export const DELETE_PERSON_INIT = 'DELETE_PERSON_INIT';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

/* Update Person */

/* (SYNC) */
export const CHANGE_FORM = 'CHANGE_FORM';

/* (ASYNC) */
export const UPDATE_PERSON_INIT = 'UPDATE_PERSON_INIT';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';

export const FETCH_PERSON_INIT = 'FETCH_PERSON_INIT';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';


/* SaveStack */

/* (ASYNC) */
export const SAVE_STACK_INIT = 'SAVE_STACK_INIT';
export const SAVE_STACK_SUCCESS = 'SAVE_STACK_SUCCESS';
export const SAVE_STACK_FAILURE = 'SAVE_STACK_FAILURE';


/* ListStack */

/* (ASYNC) */
export const FETCH_STACKS_INIT = 'FETCH_STACKS_INIT';
export const FETCH_STACKS_SUCCESS = 'FETCH_STACKS_SUCCESS';
export const FETCH_STACKS_FAILURE = 'FETCH_STACKS_FAILURE';
export const FETCH_STACKS_SUCCESSMORE = 'FETCH_STACKS_SUCCESSMORE';

export const DELETE_STACK_INIT = 'DELETE_STACK_INIT';
export const DELETE_STACK_SUCCESS = 'DELETE_STACK_SUCCESS';
export const DELETE_STACK_FAILURE = 'DELETE_STACK_FAILURE';

/* UpdateStack */

/* (ASYNC) */
export const UPDATE_STACK_INIT = 'UPDATE_STACK_INIT';
export const UPDATE_STACK_SUCCESS = 'UPDATE_STACK_SUCCESS';
export const UPDATE_STACK_FAILURE = 'UPDATE_STACK_FAILURE';

export const FETCH_STACK_INIT = 'FETCH_STACK_INIT';
export const FETCH_STACK_SUCCESS = 'FETCH_STACK_SUCCESS';
export const FETCH_STACK_FAILURE = 'FETCH_STACK_FAILURE';

/* SaveProject */

/* (ASYNC) */
export const SAVE_PROJECT_INIT = 'SAVE_PROJECT_INIT';
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';
export const SAVE_PROJECT_FAILURE = 'SAVE_PROJECT_FAILURE';

/* ListProject */

/* (ASYNC) */
export const FETCH_PROJECTS_INIT = 'FETCH_PROJECTS_INIT';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const FETCH_PROJECTS_SUCCESSMORE = 'FETCH_PROJECTS_SUCCESSMORE';

export const DELETE_PROJECT_INIT = 'DELETE_PROJECT_INIT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

/* UpdateProject */

/* (ASYNC) */
export const UPDATE_PROJECT_INIT = 'UPDATE_PROJECT_INIT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

export const FETCH_PROJECT_INIT = 'FETCH_PROJECT_INIT';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';


/* SaveTime */

/* (ASYNC) */
export const SAVE_TIME_INIT = 'SAVE_TIME_INIT';
export const SAVE_TIME_SUCCESS = 'SAVE_TIME_SUCCESS';
export const SAVE_TIME_FAILURE = 'SAVE_TIME_FAILURE';

/* ListTime */

/* (ASYNC) */
export const FETCH_TIMES_INIT = 'FETCH_TIMES_INIT';
export const FETCH_TIMES_SUCCESS = 'FETCH_TIMES_SUCCESS';
export const FETCH_TIMES_FAILURE = 'FETCH_TIMES_FAILURE';
export const FETCH_TIMES_SUCCESSMORE = 'FETCH_TIMES_SUCCESSMORE';

export const DELETE_TIME_INIT = 'DELETE_TIME_INIT';
export const DELETE_TIME_SUCCESS = 'DELETE_TIME_SUCCESS';
export const DELETE_TIME_FAILURE = 'DELETE_TIME_FAILURE';

/* UpdateTime */

/* (ASYNC) */
export const UPDATE_TIME_INIT = 'UPDATE_TIME_INIT';
export const UPDATE_TIME_SUCCESS = 'UPDATE_TIME_SUCCESS';
export const UPDATE_TIME_FAILURE = 'UPDATE_TIME_FAILURE';

export const FETCH_TIME_INIT = 'FETCH_TIME_INIT';
export const FETCH_TIME_SUCCESS = 'FETCH_TIME_SUCCESS';
export const FETCH_TIME_FAILURE = 'FETCH_TIME_FAILURE';