//Product Actions(Async)

/* SavePerson */

/* (ASYNC) */
export const SAVE_PERSON_INIT = 'SAVE_PERSON_INIT';
export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAILURE = 'SAVE_PERSON_FAILURE';

/* ListPerson */

/* (ASYNC) */
export const FETCH_PEOPLE_INIT = 'FETCH_PEOPLE_INIT';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';
export const FETCH_PEOPLE_SUCCESSMORE = 'FETCH_PEOPLE_SUCCESSMORE';

export const DELETE_PERSON_INIT = 'DELETE_PERSON_INIT';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

/* Update Person */

/* (SYNC) */
export const CHANGE_FORM = 'CHANGE_FORM';

/* (ASYNC) */
export const UPDATE_PERSON_INIT = 'UPDATE_PERSON_INIT';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';

export const FETCH_PERSON_INIT = 'FETCH_PERSON_INIT';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';
